[build]
publish = "public"
ignore = "false"
command = "node_modules/.bin/antora --html-url-extension-style=indexify --pull ../antora-playbook.yml"

[build.environment]
NODE_VERSION = "12.18.4"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

# NOTE the --fetch flag is needed on both calls to update both the content and UI bundle (since the xref validator doesn't fetch the UI)

[context.deploy-preview]
command = "node_modules/.bin/antora --html-url-extension-style=indexify --pull --url $DEPLOY_PRIME_URL ../antora-playbook.yml"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"

# ...or define headers in _headers file to allow use of netlify command (not currently used)
# /_/font/*
#  Cache-Control: public,max-age=604800
