[build]
publish = "public"
ignore = "false"

[build.environment]
CI = "true"
NODE_VERSION = "12.18.4"
# WARNING netlify-build ignores NPM_FLAGS when installing plugins, so use low-level NPM_CONFIG_ flag instead
#NPM_FLAGS = "--no-optional"
NPM_CONFIG_OPTIONAL = "false"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

# NOTE the --fetch flag is needed on both calls to update both the content and UI bundle (since the xref validator doesn't fetch the UI)

[context.production]
command = """\
node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../antora-playbook.yml && \
node_modules/.bin/antora --fetch --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public ../antora-playbook.yml && \
sed -i 's; 301$;&!;' public/_redirects && \
curl -s -X POST -F "token=$INDEX_WEBHOOK_TOKEN" -F "ref=$BRANCH" -F "variables[TRIGGER_ACTION]=index" $INDEX_WEBHOOK_URL | \
grep -oPq '"web_url":"[^"]+pipelines[^"]+"'\
"""

[context.production.environment]
ALGOLIA_APP_ID = "E80Q5UHPOS"
ALGOLIA_API_KEY = "6e7248a6d21038512a92145e9b903757"
ALGOLIA_IDX_NAME = "antora-docs"
GOOGLE_ANALYTICS_KEY = "UA-112324747-2"

[context.deploy-preview]
command = """\
node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../antora-playbook.yml && \
node_modules/.bin/antora --fetch --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public --url $DEPLOY_PRIME_URL ../antora-playbook.yml && \
sed -i 's; 301$;&!;' public/_redirects\
"""

[[plugins]]
package = "netlify-plugin-checklinks"

[plugins.inputs]
entryPoints = ["**/*.html"]
recursive = true
pretty = true
# the leading space in the skipPattern is significant
skipPatterns = [" public/index.html"]
todoPatterns = []
checkExternal = false
followSourceMaps = false

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"

# ...or define headers in _headers file to allow use of netlify command (not currently used)
# /_/font/*
#  Cache-Control: public,max-age=604800

# NOTE the following redirects get appended to the redirects defined in the _redirects file

[[redirects]]
from = "https://antora-docs.netlify.com/*"
to = "https://docs.antora.org/:splat"
status = 301
force = true

[[redirects]]
from = "/antora/1.0/*"
to = "/antora/latest/:splat"
status = 301
force = true

[[redirects]]
from = "/antora/1.1/*"
to = "/antora/latest/:splat"
status = 301
force = true

[[redirects]]
from = "/antora/latest/*"
to = "/antora/2.3/:splat"
status = 302
force = true
